route:
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: 'default-receiver'
# In the future, a Webhook can be added here to send a message to Team phones