global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'zc-nestjs-apps'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['zc-app-v30:3000']

  # - job_name: 'containers'
  #   static_configs:
  #     - targets: ['zc-web-entry:80']

# Tell Prometheus where the alarm server is located
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['zc-alertmanager:9093']

# Tell Prometheus where to read the alert rules
rule_files:
  - "/etc/prometheus/alerts.rules.yml"